# Generated by Django 6.1.1 on 2026-09-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_morador_apartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=11)),
                ('modelo', models.CharField(max_length=11)),
                ('cor', models.CharField(max_length=11)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.morador')),
            ],
        ),
    ]
