# Generated by Django 6.1.1 on 2026-10-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_morador_apartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidade', models.FloatField()),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.DateTimeField()),
                ('horario_final', models.DateTimeField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavanderia.maquina')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.morador')),
            ],
        ),
    ]
