# Generated by Django 6.1.1 on 2026-10-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_morador_apartamento'),
        ('encomendas', '0002_alter_encomendas_data_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomendas',
            name='morador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.morador'),
        ),
    ]
