# Generated by Django 6.1.1 on 2026-09-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_morador_apartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('data_chegada', models.DateTimeField(auto_now_add=True)),
                ('data_retirada', models.DateTimeField(blank=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.morador')),
            ],
        ),
    ]
