# Generated by Django 6.1.1 on 2026-09-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomendas',
            name='data_retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
