name: CI/CD Pipeline AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1 # Altere para a sua região na AWS
  ECR_REPOSITORY: o-seu-sindico-api

jobs:
  testes:
    name: Rodar Testes Automatizados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Instalar Poetry e Dependências
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          cd OSeuSindico
          poetry install

      - name: Executar Testes do Django
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DB_NAME: sqlite3
        run: |
          cd OSeuSindico/src
          python manage.py test

  deploy:
    name: Build e Deploy para AWS
    runs-on: ubuntu-latest
    needs: testes # Só roda se os testes passarem!
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, e Push no Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          
      # A partir daqui, você pode adicionar o gatilho para reiniciar o seu servidor EC2 
      # ou atualizar o seu serviço no AWS ECS usando a nova imagem do ECR.
